apiVersion: v1
kind: Pod
metadata:
  name: node
spec:
  containers:
    - env:
        - name: ENV
          value: production
        - name: port
          value: "8080"
        - name: TIMEOUT
          value: "10000"
      name: node1
      image: ansike/ansike:test-docker-node-v1
      ports:
      - containerPort: 8080
        name: node1
    - env:
        - name: ENV
          value: production
        - name: port
          value: "8090"
        - name: TIMEOUT
          value: "10000"
      name: node2
      image: ansike/ansike:test-docker-node-v1
      ports:
      - containerPort: 8090 
        name: node2
