apiVersion: v1
kind: Pod
metadata:
  name: node-gy
spec:
  containers:
    - name: node1
      image: ansike/ansike:test-1
      env:
        - name: PORT
          value: "8080"
      # command: ["sh", "-c", "sleep 3600"]
      ports:
        - containerPort: 8080
          name: node
    - name: node2
      env:
        - name: PORT
          value: "8090"
      image: ansike/ansike:test-1
      # command: ["sh", "-c", "sleep 3600"]
      ports:
        - containerPort: 8090
          name: node
