apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-mysql
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-mysql
  nfs:
    path: "/srv/nfs-mysql"
    server: 10.37.156.156
