apiVersion: v1
kind: Secret
metadata:
  name: my-secret-volume
type: Opaque
data:
  name: YWRtaW4K
  password: MTIzNDU2Cg==
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret-volume
  containers:
    - image: ansike/ansike:test-docker-node-v2
      name: pod-secret-container
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/secrets"
          readOnly: true
