apiVersion: v1
kind: Secret
metadata:
  name: my-secret-env
type: Opaque
data:
  name: YWRtaW4K
  password: MTIzNDU2Cg==
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-env
spec:
  containers:
    - image: ansike/ansike:test-docker-node-v2
      name: pod-secret-container
      env:
        - name: name
          valueFrom:
            secretKeyRef:
              name: my-secret-env
              key: name
        - name: pass
          valueFrom:
            secretKeyRef:
              name: my-secret-env
              key: password
      envFrom:
        - secretRef:
            name: my-secret-env


