apiVersion: v1
kind: Pod
metadata:
  name: node
spec:
  containers:
    - name: my-app
      image: busybox:1
      command: ["sh", "-c", "echo 'The app is running!' && sleep 3000"]
  initContainers:
    - name: init-service
      image: busybox:1
      command:
        [
          "sh",
          "-c",
          "until nslookup myservice; do echo waiting for myservice; sleep 2; done;",
        ]
    - name: init-mydb
      image: busybox:1
      command:
        [
          "sh",
          "-c",
          "until nslookup mydb; do echo waiting for mydb; sleep 2; done;",
        ]
