apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:stable-alpine
      ports:
        - containerPort: 80
          name: nginx
      livenessProbe:
        tcpSocket:
          port: 80
        periodSeconds: 3
