apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:stable-alpine
      ports:
        - containerPort: 80
          name: nginx
      livenessProbe:
        httpGet:
          port: 80
          path: /
        initialDelaySeconds: 1
        periodSeconds: 3
        timeoutSeconds: 10
