apiVersion: v1
kind: Pod
metadata:
  name: node
spec:
  containers:
    - name: node1
      image: busybox:1
      ports:
        - containerPort: 8080
          name: node1
      command:
        ["sh", "-c", "touch /tmp/live; sleep 30; rm -rf /tmp/live; sleep 3600"]
      livenessProbe:
        exec:
          command: ["test", "-e", "/tmp/live"]
        initialDelaySeconds: 1
        periodSeconds: 3
