apiVersion: v1
kind: Service
metadata:
  name: mysql-single
  namespace: web
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-single
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-single
  namespace: web
spec:
  selector:
    matchLabels:
      app: mysql-single
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-single
    spec:
      containers:
        - image: mysql:5.7
          name: mysql-single
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-single-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-single-pv-volume
  namespace: web
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data00/tmp/pvs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-single-pv-claim
  namespace: web
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
