apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-001
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/srv/nfs/redis"
    server: 10.37.156.156
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-002
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/srv/nfs/redis"
    server: 10.37.156.156