apiVersion: v1
kind: Service
metadata:
  name: redis-single
  namespace: web
spec:
  ports:
    - port: 6379
  selector:
    app: redis-single
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-single
  namespace: web
spec:
  selector:
    matchLabels:
      app: redis-single
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis-single
    spec:
      containers:
        - image: "docker.io/redis:6.0.5"
          name: redis-single
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
              name: redis
