apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  app.env: "env"
  app.port: "3001"

---
apiVersion: v1
kind: Pod
metadata:
  name: app-pod-cm
spec:
  containers:
    - name: app-container
      image: busybox:1
      command: ["sh", "-c", "env; echo 'port:$(port)'"]
      env:
        - name: env
          valueFrom:
          # 分key导入
            configMapKeyRef:
              name: app-configmap
              key: app.env
        - name: port
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: app.port
      # 全量导入
      envFrom:
        - configMapRef:
            name: app-configmap
